# Generated by Django 5.2 on 2025-05-22 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacs',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medical_reports.patient'),
        ),
    ]
