# Generated by Django 5.2 on 2025-05-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_reports', '0002_alter_pacs_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalheader',
            name='paper_size',
            field=models.CharField(blank=True, choices=[('A4', 'A4'), ('Letter', 'Letter'), ('Legal', 'Legal')], max_length=20),
        ),
    ]
