# Generated by Django 5.2 on 2025-05-22 14:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_reports', '0003_alter_hospitalheader_paper_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('terms', 'Terms & Conditions'), ('privacy', 'Privacy Policy')], max_length=20, unique=True)),
                ('content', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='ehr',
            name='auth_token',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='image',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='medical_reports.report'),
        ),
        migrations.AddField(
            model_name='report',
            name='default_actions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('review', 'Review')], default='submitted', max_length=20),
        ),
        migrations.AlterField(
            model_name='ehr',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='ehr',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medical_reports.patient'),
        ),
        migrations.AlterField(
            model_name='ehr',
            name='protocol',
            field=models.CharField(choices=[('FHIR', 'FHIR'), ('HL7', 'HL7')], max_length=50),
        ),
        migrations.AlterField(
            model_name='fieldmapping',
            name='type',
            field=models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('date', 'Date'), ('boolean', 'Boolean')], max_length=50),
        ),
        migrations.AlterField(
            model_name='hospitalheader',
            name='accreditations_position',
            field=models.CharField(blank=True, choices=[('top-left', 'Top Left'), ('top-right', 'Top Right'), ('bottom-left', 'Bottom Left'), ('bottom-right', 'Bottom Right')], max_length=20),
        ),
        migrations.AlterField(
            model_name='hospitalheader',
            name='address_position',
            field=models.CharField(blank=True, choices=[('top-left', 'Top Left'), ('top-right', 'Top Right'), ('bottom-left', 'Bottom Left'), ('bottom-right', 'Bottom Right')], max_length=20),
        ),
        migrations.AlterField(
            model_name='hospitalheader',
            name='department_position',
            field=models.CharField(blank=True, choices=[('top-left', 'Top Left'), ('top-right', 'Top Right'), ('bottom-left', 'Bottom Left'), ('bottom-right', 'Bottom Right')], max_length=20),
        ),
        migrations.AlterField(
            model_name='hospitalheader',
            name='email_position',
            field=models.CharField(blank=True, choices=[('top-left', 'Top Left'), ('top-right', 'Top Right'), ('bottom-left', 'Bottom Left'), ('bottom-right', 'Bottom Right')], max_length=20),
        ),
        migrations.AlterField(
            model_name='hospitalheader',
            name='emergency_contact_position',
            field=models.CharField(blank=True, choices=[('top-left', 'Top Left'), ('top-right', 'Top Right'), ('bottom-left', 'Bottom Left'), ('bottom-right', 'Bottom Right')], max_length=20),
        ),
        migrations.AlterField(
            model_name='hospitalheader',
            name='fax_position',
            field=models.CharField(blank=True, choices=[('top-left', 'Top Left'), ('top-right', 'Top Right'), ('bottom-left', 'Bottom Left'), ('bottom-right', 'Bottom Right')], max_length=20),
        ),
        migrations.AlterField(
            model_name='hospitalheader',
            name='font_family',
            field=models.CharField(blank=True, choices=[('Helvetica', 'Helvetica'), ('Times-Roman', 'Times Roman'), ('Courier', 'Courier')], max_length=100),
        ),
        migrations.AlterField(
            model_name='hospitalheader',
            name='header',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='hospitalheader',
            name='logo_position',
            field=models.CharField(blank=True, choices=[('left', 'Left'), ('right', 'Right')], max_length=20),
        ),
        migrations.AlterField(
            model_name='hospitalheader',
            name='name_position',
            field=models.CharField(blank=True, choices=[('top-left', 'Top Left'), ('top-right', 'Top Right'), ('bottom-left', 'Bottom Left'), ('bottom-right', 'Bottom Right')], max_length=20),
        ),
        migrations.AlterField(
            model_name='hospitalheader',
            name='phone_position',
            field=models.CharField(blank=True, choices=[('top-left', 'Top Left'), ('top-right', 'Top Right'), ('bottom-left', 'Bottom Left'), ('bottom-right', 'Bottom Right')], max_length=20),
        ),
        migrations.AlterField(
            model_name='hospitalheader',
            name='qr_code_position',
            field=models.CharField(blank=True, choices=[('top-left', 'Top Left'), ('top-right', 'Top Right'), ('bottom-left', 'Bottom Left'), ('bottom-right', 'Bottom Right')], max_length=20),
        ),
        migrations.AlterField(
            model_name='hospitalheader',
            name='website_position',
            field=models.CharField(blank=True, choices=[('top-left', 'Top Left'), ('top-right', 'Top Right'), ('bottom-left', 'Bottom Left'), ('bottom-right', 'Bottom Right')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pacs',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
