# Generated by Django 5.2 on 2025-05-22 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_reports', '0004_demorequest_policy_ehr_auth_token_image_report_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Policy',
        ),
    ]
