# Generated by Django 5.2 on 2025-06-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_reports', '0005_delete_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='visit_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ ویزیت'),
        ),
    ]
