# Generated by Django 5.2 on 2025-06-30 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_reports', '0006_patient_visit_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pacs',
            old_name='ae_title_in',
            new_name='ae_title_local',
        ),
        migrations.RenameField(
            model_name='pacs',
            old_name='ae_title_out',
            new_name='ae_title_remote',
        ),
        migrations.RenameField(
            model_name='pacs',
            old_name='ip_address',
            new_name='server_address',
        ),
        migrations.AddIndex(
            model_name='pacs',
            index=models.Index(fields=['hospital'], name='medical_rep_hospita_4b00b2_idx'),
        ),
        migrations.AddIndex(
            model_name='pacs',
            index=models.Index(fields=['patient'], name='medical_rep_patient_fecbf4_idx'),
        ),
    ]
